version: '3.4'

services:
  jurassicparkapp:
    image: cypher4859/jurassic-park:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
